---
version: "3.7"
services:
  postgres:
    image: "postgres:11"
    container_name: slotbooking_postgres
    restart: "unless-stopped"
    ports:
      - "5432:5432"
    volumes:
      - source: ./postgres/scripts/local
        target: /docker-entrypoint-initdb.d
        type: bind
        read_only: true
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=tester