spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 1
      idle-timeout: 600000
      connection-timeout: 30000
    url: jdbc:postgresql://localhost:5432/bank
    driverClassName: org.postgresql.Driver
    username: tester
    password: tester
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
      table-name: ACCOUNT_USER_SESSION
      cleanup-cron: "-"

server:
  port: 9999